name: 'Integration test'
run-name: 'Integration Test'
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run Storybook
        run: |
          yarn
          yarn build
          cd example/storybook
          yarn storybook &

      - name: Wait for server to start
        run: sleep 100

      - name: Run tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: |
          yarn test
